echo off
echo ********************************************
echo *     P R I N C E   O F   P E R S I A      *        Print the file
echo * ---------------------------------------- *
echo *     , 8  : Jump/climb or Defence up     *        "PASSWORD.TXT"
echo *     , 2  : Knee/climb down              *
echo *   - , 4  : Run to left                  *        before starting
echo *   - , 6  : Run to right                 *
echo *  Home, 7  : Jump or Defence left         *        this game !
echo *  PgUp, 9  : Jump or Defence right        *
echo *  Shift-- : One step to left             *
echo *  Shift-- : One step to right            *
echo *  Shift    : Drink, Fetch or Attack       *
echo *  Ctrl-K   : Use keyboard                 *
echo *  Ctrl-J   : Use joystick                 *
echo *  Ctrl-A   : Restart Level                *
echo *  Ctrl-R   : Reboot the game              *
echo *  Ctrl-S   : Toggle sound on/off          *
echo *  Ctrl-G   : Save game (after level 3)    *
echo *  Ctrl-L   : Load saved level at startup  *
echo *  Shift-L  : Skip 1 level up to level 4   *
echo *  Space    : Show time left               *
echo *  ESC      : Pause                        *
echo *  Ctrl-Q   : Quit to DOS                  *
echo ********************************************
pause
echo on
@echo off
pause
@echo on
prince
cd \
dir 